main: main.c frequency.c sort.c tree.c assign_num.c compress.c
	gcc main.c frequency.c sort.c tree.c assign_num.c compress.c -o main
debug: main.c frequency.c sort.c tree.c assign_num.c compress.c
	gcc main.c frequency.c sort.c tree.c assign_num.c compress.c -g3 -Og -Wall -Wextra -fsanitize=address,undefined -o main
